# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Teamply' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'
  pod 'FSCalendar'
  pod 'MaterialComponents/BottomSheet'
  pod 'PanModal'
  pod 'Moya'
  pod 'Tabman'

  # Pods for Teamply
  # Workaround for Cocoapods issue #7606
  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
       end
  end
end
