# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Teamply' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'
  pod 'FSCalendar'
  
  # Pods for Teamply

end
